### ISSUE TITLE
renv.lock pins a GenSA that no longer compiles (R >= 4.5 removed SET_TYPEOF)

### ISSUE THREAD

**Issue by mufflyt** [mufflyt/cliff#27]
## Summary

`renv::restore()` cannot complete on current R: the pinned `GenSA` fails to compile because it uses `SET_TYPEOF`, which is no longer part of R's API. This cascades into `eulerr`, so the environment is not reproducible as pinned.

## Error

Surfaced by the `mufflyaccess` cross-repo integration job ([run](https://github.com/mufflyt/mufflyaccess/actions/runs/31767974787)), on `ubuntu-latest` with **R 4.6.1**:

```
Engine.cpp:857:5: error: 'SET_TYPEOF' was not declared in this scope; did you mean 'TYPEOF'?
ERROR: compilation failed for package 'GenSA'

- [GenSA]: install failed
- [eulerr]: dependency failed (GenSA)
Error: failed to install "GenSA", "eulerr"
```

`SET_TYPEOF` was removed from the R API in recent versions, so the pinned `GenSA` source cannot build against R ≥ 4.5.

An earlier run of the same job also failed on missing system libraries for `textshaping` / `ragg` / `gdtools` (harfbuzz, fribidi, cairo). Those are now installed on the mufflyaccess side, so `GenSA` is the remaining blocker.

## Why it matters

The lockfile no longer restores on a current R toolchain. Existing machines are fine because the packages are already built there, which is exactly why this stayed hidden. Any clean restore — CI, a new machine, a collaborator — fails.

## Suggested fix

Options, roughly in order of preference:

- **Update the pin** to a `GenSA` release that builds on R ≥ 4.5 (check whether upstream has patched it; if not, this may need `Remotes:` or a fork).
- **Drop it** if `eulerr` is only used for figures and is not needed by the URPS contract or engine paths — the smallest change if the dependency is incidental.
- **Pin R** to an older version in cliff's own workflows. This restores reproducibility but defers the incompatibility rather than resolving it.

## Context: what this is blocking

`mufflyaccess`'s `isochrones-integration` workflow runs cliff's URPS contract tests against the **current** mufflyaccess checkout. That job had never actually executed — it was gated behind a cross-repo token that was never set, and reported green while skipping every step. Now that it runs, cliff cannot get past dependency restore.

Specifically, it is blocking verification of a **collaborator-facing contract change** in mufflyaccess ([`af57a17`](https://github.com/mufflyt/mufflyaccess/commit/af57a17)):

1. **Schema**: a new `retirement_status` column (`observed` / `partially_observed` / `not_ascertained`).
2. **Data semantics**: `n_retired` is now `NA` where retirement was never ascertained, having previously been published as `0`.

Whether cliff tolerates that is currently unknown, because its tests cannot run.

## Related — worth a separate look

`renv.lock` pins mufflyaccess at `b1f33acf9`, roughly **20 commits behind** `main`, while recording it as version `0.10.0` (twostep pins a *different* commit, also labelled `0.10.0`). That pin predates the retirement correction above, so cliff is currently consuming a mufflyaccess that still reports `n_retired = 0` — i.e. a known absence of retirement — where the correct value is "not ascertained".

This matters more for cliff than for most consumers: cliff owns the entries-and-exits panel and the workforce-cliff supply/demand line, so treating unascertained retirement as zero departures understates attrition directly.

`NA` here must not be read as, or replaced with, zero.

**Comment by mufflyt** [comment]
Resolved: the premise does not hold on R 4.5.3.

GenSA 1.1.15 installs as a plain **binary**, no compilation:

```
✔ GenSA 1.1.15   [262 kB in 0.24s]
✔ GenSA 1.1.15   [installed binary]
```

Reproduced in two independent clean-restore runs into empty libraries under R 4.5.3 (acceptance gate for #37). The original diagnosis assumed a source build; RSPM/CRAN serve a binary for this platform, so `SET_TYPEOF` is never reached.

This is now checked continuously rather than assumed: the nightly `renv.lock restores from nothing` job (`.github/workflows/nightly.yml`) restores the full lockfile into an empty library and reports GenSA's version explicitly, so a regression would surface the next night rather than at the next pin bump.

Note the restore did originally fail on this machine, but for an unrelated reason: the V8 binary links against `libnode.so.109`, which the runner lacked. Fixed by adding `libnode-dev` (86a0acc).
